# Generated by Django 3.1.3 on 2020-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_read',
        ),
        migrations.AddField(
            model_name='user',
            name='is_read_list',
            field=models.ManyToManyField(blank=True, related_name='is_read_post', to='blog.Post'),
        ),
    ]
